/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './../galaxies/__root'

// Create Virtual Routes

const TodoListIndexLazyImport = createFileRoute('/todo-list/')()
const FormIndexLazyImport = createFileRoute('/form/')()
const BaseListIndexLazyImport = createFileRoute('/base-list/')()
const FormBasicIndexLazyImport = createFileRoute('/form/basic/')()
const FormAntdIndexLazyImport = createFileRoute('/form/antd/')()

// Create/Update Routes

const TodoListIndexLazyRoute = TodoListIndexLazyImport.update({
  id: '/todo-list/',
  path: '/todo-list/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./../galaxies/todo-list/index.lazy').then((d) => d.Route),
)

const FormIndexLazyRoute = FormIndexLazyImport.update({
  id: '/form/',
  path: '/form/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./../galaxies/form/index.lazy').then((d) => d.Route),
)

const BaseListIndexLazyRoute = BaseListIndexLazyImport.update({
  id: '/base-list/',
  path: '/base-list/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./../galaxies/base-list/index.lazy').then((d) => d.Route),
)

const FormBasicIndexLazyRoute = FormBasicIndexLazyImport.update({
  id: '/form/basic/',
  path: '/form/basic/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./../galaxies/form/basic/index.lazy').then((d) => d.Route),
)

const FormAntdIndexLazyRoute = FormAntdIndexLazyImport.update({
  id: '/form/antd/',
  path: '/form/antd/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./../galaxies/form/antd/index.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/base-list/': {
      id: '/base-list/'
      path: '/base-list'
      fullPath: '/base-list'
      preLoaderRoute: typeof BaseListIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/form/': {
      id: '/form/'
      path: '/form'
      fullPath: '/form'
      preLoaderRoute: typeof FormIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/todo-list/': {
      id: '/todo-list/'
      path: '/todo-list'
      fullPath: '/todo-list'
      preLoaderRoute: typeof TodoListIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/form/antd/': {
      id: '/form/antd/'
      path: '/form/antd'
      fullPath: '/form/antd'
      preLoaderRoute: typeof FormAntdIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/form/basic/': {
      id: '/form/basic/'
      path: '/form/basic'
      fullPath: '/form/basic'
      preLoaderRoute: typeof FormBasicIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/base-list': typeof BaseListIndexLazyRoute
  '/form': typeof FormIndexLazyRoute
  '/todo-list': typeof TodoListIndexLazyRoute
  '/form/antd': typeof FormAntdIndexLazyRoute
  '/form/basic': typeof FormBasicIndexLazyRoute
}

export interface FileRoutesByTo {
  '/base-list': typeof BaseListIndexLazyRoute
  '/form': typeof FormIndexLazyRoute
  '/todo-list': typeof TodoListIndexLazyRoute
  '/form/antd': typeof FormAntdIndexLazyRoute
  '/form/basic': typeof FormBasicIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/base-list/': typeof BaseListIndexLazyRoute
  '/form/': typeof FormIndexLazyRoute
  '/todo-list/': typeof TodoListIndexLazyRoute
  '/form/antd/': typeof FormAntdIndexLazyRoute
  '/form/basic/': typeof FormBasicIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/base-list'
    | '/form'
    | '/todo-list'
    | '/form/antd'
    | '/form/basic'
  fileRoutesByTo: FileRoutesByTo
  to: '/base-list' | '/form' | '/todo-list' | '/form/antd' | '/form/basic'
  id:
    | '__root__'
    | '/base-list/'
    | '/form/'
    | '/todo-list/'
    | '/form/antd/'
    | '/form/basic/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  BaseListIndexLazyRoute: typeof BaseListIndexLazyRoute
  FormIndexLazyRoute: typeof FormIndexLazyRoute
  TodoListIndexLazyRoute: typeof TodoListIndexLazyRoute
  FormAntdIndexLazyRoute: typeof FormAntdIndexLazyRoute
  FormBasicIndexLazyRoute: typeof FormBasicIndexLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  BaseListIndexLazyRoute: BaseListIndexLazyRoute,
  FormIndexLazyRoute: FormIndexLazyRoute,
  TodoListIndexLazyRoute: TodoListIndexLazyRoute,
  FormAntdIndexLazyRoute: FormAntdIndexLazyRoute,
  FormBasicIndexLazyRoute: FormBasicIndexLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/base-list/",
        "/form/",
        "/todo-list/",
        "/form/antd/",
        "/form/basic/"
      ]
    },
    "/base-list/": {
      "filePath": "base-list/index.lazy.tsx"
    },
    "/form/": {
      "filePath": "form/index.lazy.tsx"
    },
    "/todo-list/": {
      "filePath": "todo-list/index.lazy.tsx"
    },
    "/form/antd/": {
      "filePath": "form/antd/index.lazy.tsx"
    },
    "/form/basic/": {
      "filePath": "form/basic/index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
